using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using NPlot;

namespace Warps.Controls
{
	public partial class GuideEditor : UserControl
	{
		public GuideEditor(GuideComb comb)
		{
			InitializeComponent();
			Comb = comb;
			InitializeDGV();
			//InitializePlotterComponents();
		}

		RBF.RBFSpline rbf = new RBF.RBFSpline();
	
		public string Label
		{
			get { return m_curveEditor.Label; }
			set { m_curveEditor.Label = value; }
		}

		public int Count
		{
			get { return m_curveEditor.Count; }
			set { m_curveEditor.Count = value; }
		}

		public PointTypeSwitcher this[int index]
		{
			get { return m_curveEditor[index]; }
		}

		public double Length
		{
			set { m_curveEditor.Length = value; }
		}

		public IFitPoint[] FitPoints
		{
			//get { return m_curveEditor.FitPoints; }
			set { m_curveEditor.FitPoints = value; }
		}

		public MouldCurve Curve
		{
			get { return m_curveEditor.Curve; }
			set { m_curveEditor.Curve = value; }
		}

		private void InitializeDGV()
		{
			m_dgv.Rows.Clear();
			m_dgv.Columns.Add("S", "Pos");
			m_dgv.Columns[m_dgv.Columns.Count - 1].Width = 50;
			m_dgv.Columns.Add("P", "DPI");
			m_dgv.Columns[m_dgv.Columns.Count - 1].Width = 50;

			m_dgv.RowHeadersVisible = false;
			LoadCombPoints();
			UpdatePlot();
		}

		private void LoadCombPoints()
		{
			if (Comb != null)
			{
				foreach (Vect2 pnt in Comb.CombPnts)
					m_dgv.Rows.Add(new object[] { pnt[0], pnt[1] });
			}
		}

		GuideComb m_comb = null;

		public GuideComb Comb
		{
			get { return m_comb; }
			set { m_comb = value; }
		}

		#region NPLOT STUFF

		public void InitializePlotterComponents()
		{
			m_plot.Clear();
			m_plot.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
			//curvePlot.BackColor = Color.Black;
			//curvePlot.ForeColor = Color.White;
			//curvePlot.PlotBackColor = Color.Black;

			NPlot.Grid grid = new NPlot.Grid();
			grid.VerticalGridType = NPlot.Grid.GridType.Coarse;
			grid.HorizontalGridType = NPlot.Grid.GridType.Coarse;
			grid.MinorGridPen = new Pen(Color.Blue, 1.0f);
			grid.MajorGridPen = new Pen(Color.LightGray, 1.0f);

			m_plot.Add(grid);

			StepPlot stepBalance = new StepPlot();
			stepBalance.Pen = new Pen(Color.Green, 2);

			List<Int32> balanceAxis = new List<Int32>();

			List<decimal> balanceAmount = new List<decimal>();

			for (int i = 0; i < 25; i++)
			{
				balanceAxis.Add(0);
			}

			stepBalance.AbscissaData = balanceAxis;
			stepBalance.DataSource = balanceAmount;
			m_plot.Add(stepBalance);
			m_plot.ShowCoordinates = true;
			//curvePlot.AutoScaleAutoGeneratedAxes = true;

			m_plot.RightMenu = NPlot.Windows.PlotSurface2D.DefaultContextMenu;
			m_plot.AddInteraction(new NPlot.Windows.PlotSurface2D.Interactions.AxisDrag(false));
			//curvePlot.AddInteraction(new NPlot.Windows.PlotSurface2D.Interactions.HorizontalDrag());
			//curvePlot.AddInteraction(new NPlot.Windows.PlotSurface2D.Interactions.VerticalDrag());

			m_plot.AddAxesConstraint(new AxesConstraint.AxisPosition(PlotSurface2D.YAxisPosition.Left, 60));
			//curvePlot.YAxis1.
			m_plot.YAxis1.Label = "P";
			m_plot.YAxis1.LabelFont = new Font(this.Font, FontStyle.Bold);
			m_plot.YAxis1.LabelOffsetAbsolute = true;
			m_plot.XAxis1.Label = "S";
			m_plot.XAxis1.LabelFont = new Font(this.Font, FontStyle.Bold);
			m_plot.YAxis1.LabelOffset = 30;
			m_plot.XAxis1.HideTickText = false;
			m_plot.Padding = 5;

			//curvePlot.RightMenu = NPlot.Windows.PlotSurface2D.DefaultContextMenu;
			//curvePlot.AddInteraction(new NPlot.Windows.PlotSurface2D.Interactions.AxisDrag(false));

			//curvePlot.Title = "Mold Curves";

			m_plot.TitleFont = new Font(this.Font, FontStyle.Bold);
			//Refresh surfaces.
			//if (!m_mouseDragging)
			//	curvePlot.Refresh();
		}

		public void UpdatePlot()
		{
			FitRBF();

			m_plot.Clear();
			m_plot.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;

			NPlot.Grid grid = new NPlot.Grid();
			grid.VerticalGridType = NPlot.Grid.GridType.Coarse;
			grid.HorizontalGridType = NPlot.Grid.GridType.Coarse;
			grid.MinorGridPen = new Pen(Color.Blue, 1.0f);
			grid.MajorGridPen = new Pen(Color.LightGray, 1.0f);

			m_plot.Add(grid);

			LinePlot stepBalance = new LinePlot();
			stepBalance.Pen = new Pen(Color.Green, 2);

			List<decimal> balanceAxis = new List<decimal>();

			List<decimal> balanceAmount = new List<decimal>();

			double[] p = new double[1];
			double s = 0; int CNT = 50;
			for (int i = 0; i < CNT; i++)
			{
				s = BLAS.interpolant(i, CNT);
				rbf.BsVal(s, ref p);
				balanceAxis.Add(Convert.ToDecimal(s)); 
				balanceAmount.Add(Convert.ToDecimal(p[0]));
			}	

			stepBalance.AbscissaData = balanceAxis;
			stepBalance.DataSource = balanceAmount;
			m_plot.Add(stepBalance);
			m_plot.ShowCoordinates = true;
			//curvePlot.AutoScaleAutoGeneratedAxes = true;

			m_plot.RightMenu = NPlot.Windows.PlotSurface2D.DefaultContextMenu;
			m_plot.AddInteraction(new NPlot.Windows.PlotSurface2D.Interactions.AxisDrag(false));

			//m_plot.AddAxesConstraint(new AxesConstraint.AxisPosition(PlotSurface2D.YAxisPosition.Left, 60));
			//m_plot.YAxis1.Label = "";
			//m_plot.YAxis1.LabelFont = new Font(this.Font, FontStyle.Bold);
			//m_plot.YAxis1.LabelOffsetAbsolute = true;
			//m_plot.XAxis1.Label = "";
			//m_plot.XAxis1.LabelFont = new Font(this.Font, FontStyle.Bold);
			//m_plot.YAxis1.LabelOffset = 30;
			m_plot.XAxis1.HideTickText = false;
			m_plot.Refresh();
			//m_plot.Padding = 5;

//			m_plot.TitleFont = new Font(this.Font, FontStyle.Bold);
		}

		private void FitRBF()
		{
			List<double[]> x = new List<double[]>();
			List<double> s = new List<double>();
			for (int i = 0; i < CombPnts.Length; i++)
			{
				s.Add(CombPnts[i][0]);
				x.Add(new double[] { CombPnts[i][1]});
			}	

			rbf.Fit(s, x);
		}

		#endregion NPLOT STUFF

		
		#region DataGridView stuff

		private void m_dgv_CellValueChanged(object sender, DataGridViewCellEventArgs e)
		{
			
		}

		#endregion

		public Vect2[] CombPnts 
		{ 
			get {
				List<Vect2> ret = new List<Vect2>();
				//m_dgv.Sort(m_dgv.Columns[0], ListSortDirection.Ascending);//sort by spos first
				for (int i = 0; i < m_dgv.Rows.Count - 1; i++)
				{
					ret.Add(new Vect2(Convert.ToDouble(m_dgv[0, i].Value), Convert.ToDouble(m_dgv[1, i].Value)));
				}

				return ret.ToArray();
			}
			set
			{
				m_dgv.Rows.Clear();
				foreach (Vect2 v in value)
					m_dgv.Rows.Add(v[0], v[1]);
			}
		}

		private void button1_Click(object sender, EventArgs e)
		{
			UpdatePlot();
		}
	}
}
