namespace Warps.Controls
{
	partial class GuideEditor
	{
		/// <summary> 
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Component Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this.button1 = new System.Windows.Forms.Button();
			this.m_dgv = new System.Windows.Forms.DataGridView();
			this.groupBox2 = new System.Windows.Forms.GroupBox();
			this.m_curveEditor = new Warps.CurveEditor();
			this.m_nsPlot = new Warps.NsPlot();
			this.groupBox1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.m_dgv)).BeginInit();
			this.groupBox2.SuspendLayout();
			this.SuspendLayout();
			// 
			// groupBox1
			// 
			this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.groupBox1.Controls.Add(this.m_nsPlot);
			this.groupBox1.Controls.Add(this.button1);
			this.groupBox1.Controls.Add(this.m_dgv);
			this.groupBox1.Location = new System.Drawing.Point(4, 307);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(369, 197);
			this.groupBox1.TabIndex = 1;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "Guide Height";
			// 
			// button1
			// 
			this.button1.BackColor = System.Drawing.SystemColors.ControlLightLight;
			this.button1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.button1.Location = new System.Drawing.Point(6, 168);
			this.button1.Name = "button1";
			this.button1.Size = new System.Drawing.Size(126, 23);
			this.button1.TabIndex = 4;
			this.button1.Text = "Plot";
			this.button1.UseVisualStyleBackColor = false;
			this.button1.Click += new System.EventHandler(this.plot_Click);
			// 
			// m_dgv
			// 
			this.m_dgv.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.m_dgv.Location = new System.Drawing.Point(6, 18);
			this.m_dgv.Name = "m_dgv";
			this.m_dgv.Size = new System.Drawing.Size(126, 144);
			this.m_dgv.TabIndex = 0;
			this.m_dgv.CellValueChanged += new System.Windows.Forms.DataGridViewCellEventHandler(this.m_dgv_CellValueChanged);
			// 
			// groupBox2
			// 
			this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.groupBox2.Controls.Add(this.m_curveEditor);
			this.groupBox2.Location = new System.Drawing.Point(4, 3);
			this.groupBox2.Name = "groupBox2";
			this.groupBox2.Size = new System.Drawing.Size(369, 298);
			this.groupBox2.TabIndex = 2;
			this.groupBox2.TabStop = false;
			this.groupBox2.Text = "Curve Editor";
			// 
			// m_curveEditor
			// 
			this.m_curveEditor.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this.m_curveEditor.Count = 0;
			this.m_curveEditor.Dock = System.Windows.Forms.DockStyle.Fill;
			this.m_curveEditor.Editing = false;
			this.m_curveEditor.HighLighted = false;
			this.m_curveEditor.Label = "";
			this.m_curveEditor.Location = new System.Drawing.Point(3, 16);
			this.m_curveEditor.Name = "m_curveEditor";
			this.m_curveEditor.Size = new System.Drawing.Size(363, 279);
			this.m_curveEditor.TabIndex = 0;
			// 
			// m_nsPlot
			// 
			this.m_nsPlot.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.m_nsPlot.AutoScaleAutoGeneratedAxes = false;
			this.m_nsPlot.AutoScaleTitle = false;
			this.m_nsPlot.BackColor = System.Drawing.SystemColors.ControlLightLight;
			this.m_nsPlot.DateTimeToolTip = false;
			this.m_nsPlot.Legend = null;
			this.m_nsPlot.LegendZOrder = -1;
			this.m_nsPlot.Location = new System.Drawing.Point(138, 18);
			this.m_nsPlot.Name = "m_nsPlot";
			this.m_nsPlot.RightMenu = null;
			this.m_nsPlot.ShowCoordinates = true;
			this.m_nsPlot.Size = new System.Drawing.Size(225, 173);
			this.m_nsPlot.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
			this.m_nsPlot.TabIndex = 5;
			this.m_nsPlot.Text = "Comb";
			this.m_nsPlot.Title = "";
			this.m_nsPlot.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
			this.m_nsPlot.XAxis1 = null;
			this.m_nsPlot.XAxis2 = null;
			this.m_nsPlot.YAxis1 = null;
			this.m_nsPlot.YAxis2 = null;
			// 
			// GuideEditor
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.Controls.Add(this.groupBox2);
			this.Controls.Add(this.groupBox1);
			this.Name = "GuideEditor";
			this.Size = new System.Drawing.Size(376, 507);
			this.groupBox1.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.m_dgv)).EndInit();
			this.groupBox2.ResumeLayout(false);
			this.ResumeLayout(false);

		}

		#endregion

		private CurveEditor m_curveEditor;
		private System.Windows.Forms.GroupBox groupBox1;
		private System.Windows.Forms.DataGridView m_dgv;
		private System.Windows.Forms.Button button1;
		private System.Windows.Forms.GroupBox groupBox2;
		private NsPlot m_nsPlot;
	}
}
